const datas = [
  {
    id: "1",
    name: "John Doe",
    age: 28,
    location: "New York",
    interests: ["hiking", "photography"],
    language: "English",
  },
  {
    id: "2",
    name: "Alice Smith",
    age: 24,
    location: "Los Angeles",
    interests: ["painting", "reading"],
    language: "English",
  },
  {
    id: "3",
    name: "Mohammed Khan",
    age: 32,
    location: "Dubai",
    interests: ["traveling", "cooking"],
    language: "Arabic",
  },
  {
    id: "4",
    name: "Sophie Martin",
    age: 29,
    location: "Paris",
    interests: ["dancing", "movies"],
    language: "French",
  },
  {
    id: "5",
    name: "Luis Rodriguez",
    age: 26,
    location: "Madrid",
    interests: ["football", "gaming"],
    language: "Spanish",
  },
  {
    id: "6",
    name: "Marta Gómez",
    age: 31,
    location: "Barcelona",
    interests: ["reading", "cooking"],
    language: "Spanish",
  },
  {
    id: "7",
    name: "Yuki Tanaka",
    age: 27,
    location: "Tokyo",
    interests: ["anime", "gardening"],
    language: "Japanese",
  },
  {
    id: "8",
    name: "Elena Petrova",
    age: 35,
    location: "Moscow",
    interests: ["piano", "skiing"],
    language: "Russian",
  },
  {
    id: "9",
    name: "Sebastian Müller",
    age: 23,
    location: "Berlin",
    interests: ["coding", "travelling"],
    language: "German",
  },
  {
    id: "10",
    name: "Isabella Rossi",
    age: 30,
    location: "Rome",
    interests: ["history", "art"],
    language: "Italian",
  },
];

module.exports = datas;
